name: Java Fuzzer Workflow

on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  fuzzing:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # Set up Java environment
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    # Make the Linux executable executable
    - name: Make Fuzzer Executable
      run: chmod +x ./html_parser_linux_x86_64
    
    # Run the fuzzer and fail the workflow if it returns non-zero
    - name: Run Fuzzer
      run: |
        java Fuzzer.java ./html_parser_linux_x86_64
        exit_code=$?
        if [ $exit_code -ne 0 ]; then
          echo "Fuzzer failed with exit code $exit_code"
          exit $exit_code
        fi
